//
//  Constants_Images.h
//  Rover
//
//  Created by Sean Fitzgerald on 3/9/14.
//  Copyright (c) 2014 Sean T Fitzgerald. All rights reserved.
//

#ifndef Rover_Constants_Images_h
#define Rover_Constants_Images_h

#define RV_IMAGES_LAUNCH_SCREEN_BACKGROUND (@"backgroundlaunchScreen.png")
#define RV_IMAGES_LAUNCH_SCREEN_MONTAGE_PLUTO (@[@"launchSequence0.png",@"launchSequence1.png",@"launchSequence2.png",@"launchSequence3.png",@"launchSequence4.png",@"launchSequence5Pluto.png",@"launchSequence6Pluto.png",@"launchSequence7Pluto.png",@"launchSequence8Pluto.png",@"launchSequence9Pluto.png",@"launchSequence10Pluto.png",@"launchSequence11Pluto.png",@"launchSequence12Pluto.png",@"launchSequence13Pluto.png",@"launchSequence14Pluto.png"]) //put the names with the format @"NAME", separated by commas
#define RV_IMAGES_LAUNCH_SCREEN_MONTAGE_TITAN (@[@"launchSequence0.png",@"launchSequence1.png",@"launchSequence2.png",@"launchSequence3.png",@"launchSequence4.png",@"launchSequence5Titan.png",@"launchSequence6Titan.png",@"launchSequence7Titan.png",@"launchSequence8Titan.png",@"launchSequence9Titan.png",@"launchSequence10Titan.png",@"launchSequence11Titan.png",@"launchSequence12Titan.png",@"launchSequence13Titan.png",@"launchSequence14Titan.png"]) //put the names with the format @"NAME", separated by commas
#define RV_IMAGES_LAUNCH_SCREEN_MONTAGE_MARS (@[@"launchSequence0.png",@"launchSequence1.png",@"launchSequence2.png",@"launchSequence3.png",@"launchSequence4.png",@"launchSequence5Mars.png",@"launchSequence6Mars.png",@"launchSequence7Mars.png",@"launchSequence8Mars.png",@"launchSequence9Mars.png",@"launchSequence10Mars.png",@"launchSequence11Mars.png",@"launchSequence12Mars.png",@"launchSequence13Mars.png",@"launchSequence14Mars.png"]) //put the names with the format @"NAME", separated by commas
#define RV_IMAGES_LAUNCH_SCREEN_MONTAGE_MOON (@[@"launchSequence0.png",@"launchSequence1.png",@"launchSequence2.png",@"launchSequence3.png",@"launchSequence4.png",@"launchSequence5Moon.png",@"launchSequence6Moon.png",@"launchSequence7Moon.png",@"launchSequence8Moon.png",@"launchSequence9Moon.png",@"launchSequence10Moon.png",@"launchSequence11Moon.png",@"launchSequence12Moon.png",@"launchSequence13Moon.png",@"launchSequence14Moon.png"]) //put the names with the format @"NAME", separated by commas

#define RV_IMAGES_TITLE_SCREEN_BACKGROUND (@"backgroundTitleScreen.png")
#define RV_IMAGES_TITLE_SCREEN_START_BUTTON_UP (@"startButton.png")
#define RV_IMAGES_TITLE_SCREEN_START_BUTTON_DOWN (@"startButtonDown.png")

#define RV_IMAGES_PLANET_SELECT_SCREEN_MOON_GLOW (@"moonGlow.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_TITAN_GLOW (@"titanGlow.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_MARS_GLOW (@"marsGlow.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_PLUTO_GLOW (@"plutoGlow.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_EXIT_BUTTON (@"exitButton.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_EXIT_BUTTON_DOWN (@"exitButtonDown.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_LETS_GO_BUTTON (@"buildRoverButton")
#define RV_IMAGES_PLANET_SELECT_SCREEN_LETS_GO_BUTTON_DOWN (@"buildRoverButtonDown.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_LETS_GO_BUTTON_GLOW (@"checkMark.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_PLANET_INFORMATION_MARS (@"marsDescription.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_PLANET_INFORMATION_MOON (@"moonDescription.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_PLANET_INFORMATION_PLUTO (@"plutoDescription.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_PLANET_INFORMATION_TITAN (@"titanDescription.png")
#define RV_IMAGES_PLANET_SELECT_SCREEN_BACKGROUND (@"backgroundPlanetSelectScreen.png")

#define RV_IMAGES_ROVER_BUILD_SCREEN_BACKGROUND (@"backgroundRoverBuildScreen.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_SCROLLBAR (@"scrollBarNubs.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TOOL_TYPE_BUTTONS_ANALYSIS_UP (@"toolButtonsAnalysisButtonDown_replacement.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TOOL_TYPE_BUTTONS_TRANSPORTATION_UP (@"toolButtonsLocomotionButtonDown_replacement.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TOOL_TYPE_BUTTONS_COMMUNICATION_UP (@"toolButtonsCommunicationButtonDown_replacement.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_COMMUNICATION_TOOLS_SHADOWS (@"CommunicationToolShadows.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_COMMUNICATION_TOOLS_PANCAM (@"panCam.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_COMMUNICATION_TOOLS_LGANTENNA (@"lowGainAntenna.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_COMMUNICATION_TOOLS_HGANTENNA (@"highGainAntenna.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TRANSPORTATION_TOOLS_SHADOWS (@"LocomotionToolShadows.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TRANSPORTATION_TOOLS_WHEELS (@"wheels.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TRANSPORTATION_TOOLS_TREADS (@"treads.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TRANSPORTATION_TOOLS_HOVERCRAFT (@"hovercraft.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_SHADOWS (@"AnalysisToolShadows.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_MICROSCOPE (@"microscope.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_ROCK_GRINDER (@"rockGrinder.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_SPECTROMETER (@"spectrometer.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_CHEMCAM (@"chemCam.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_WEATHER_STATION (@"weatherStation.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_LASER_DRILL (@"laserDrill.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_LAUNCH_ROVER_BUTTON (@"launchRoverButton.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_LAUNCH_ROVER_BUTTON_DOWN (@"launchRoverButtonDown.png")
#define RV_IMAGES_ROVER_BUILD_SCREEN_LAUNCH_ROVER_BUTTON_GLOW (@"letsGoButtonGlow.png")

#define RV_IMAGES_GAME_PLAY_SCREEN_BACKGROUND (@"backgroundGamePlayScreen.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_MAP_PLUTO (@"pluto.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_MAP_MARS (@"mars.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_MAP_TITAN (@"titan.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_MAP_MOON (@"moon.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMMMAND_LINEUP_BACKGROUND (@"commandLineupBackground.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_UNDO_BUTTON (@"undoButton.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_UNDO_BUTTON_DOWN (@"undoButtonDown.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_SEND_COMMAND_BUTTON (@"sendCommandButton.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_SEND_COMMAND_BUTTON_DOWN (@"sendCommandButtonDown.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_MOVE_FORWARD_BUTTON (@"moveForwardButton.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_MOVE_FORWARD_BUTTON_DOWN (@"moveForwardButtonDown.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_ANALYZE_BUTTON (@"analyzeButton.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_ANALYZE_BUTTON_DOWN (@"analyzeButtonDown.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROBOT_ARM_BUTTON (@"robotArmButton.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROBOT_ARM_BUTTON_DOWN (@"robotArmButtonDown.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_LEFT_BUTTON (@"turnLeftButton.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_LEFT_BUTTON_DOWN (@"turnLeftButtonDown.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_AROUND_BUTTON (@"turnAroundButton.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_AROUND_BUTTON_DOWN (@"turnAroundButtonDown.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_RIGHT_BUTTON (@"turnRightButton.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_RIGHT_BUTTON_DOWN (@"turnRightButtonDown.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_BATTERY_IMAGE_4 (@"battery4.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_BATTERY_IMAGE_3 (@"battery3.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_BATTERY_IMAGE_2 (@"battery2.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_BATTERY_IMAGE_1 (@"battery1.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_BATTERY_IMAGE_1_RED (@"battery1Red.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_TEXT_1 (@"compassRoseObjective1.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_TEXT_2 (@"compassRoseObjective2.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_TEXT_3 (@"compassRoseObjective3.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_OUTER (@"compassRoseLargeCircle.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_INNER (@"compassRoseSmallCircle.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_ARROW (@"compassRoseArrow.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROCK_MARS (@"BreakableRockMars.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROCK_TITAN (@"BreakableRockTitan.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROCK_PLUTO (@"BreakableRockPluto.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROCK_MOON (@"BreakableRockMoon.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_OBJECTIVE (@"objective.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_YES (@"tutorialYes.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_YES_DOWN (@"tutorialYesDown.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_NO (@"tutorialNo.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_NO_DOWN (@"tutorialNoDown.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_1 (@"tutorial1.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_2 (@"tutorial2.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_3 (@"tutorial3.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_4 (@"tutorial4.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_5 (@"tutorial5.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_6 (@"tutorial6.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_7 (@"tutorial7.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_8 (@"tutorial8.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_9 (@"tutorial9.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TRASMITTING_SIGNAL (@"transmittingSignal.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_RECEIVING_SIGNAL (@"receivingSignal.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_PLUTO_TRASMITTING_SIGNAL (@"plutoTransmittingSignal.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_PLUTO_RECEIVING_SIGNAL (@"plutoReceivingSignal.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_MARS_TRASMITTING_SIGNAL (@"marsTransmittingSignal.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_MARS_RECEIVING_SIGNAL (@"marsReceivingSignal.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_MOON_TRASMITTING_SIGNAL (@"moonTransmittingSignal.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_MOON_RECEIVING_SIGNAL (@"mooonReceivingSignal.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TITAN_TRASMITTING_SIGNAL (@"titanTransmittingSignal.png")
#define RV_IMAGES_GAME_PLAY_SCREEN_TITAN_RECEIVING_SIGNAL (@"titanReceivingSignal.png")

#define RV_MAP_PATH_INIT_IMAGE_NAME (@"mapPathInit.png")
#define RV_MAP_PATH_STRAIGHT_IMAGE_NAME (@"mapPathStraight.png")
#define RV_MAP_PATH_STRAIGHT_END_IMAGE_NAME (@"mapPathStraightEnd.png")
#define RV_MAP_PATH_CURVED_IMAGE_NAME (@"mapPathCurved.png")
#define RV_MAP_PATH_CURVED_END_IMAGE_NAME (@"mapPathCurvedEnd.png")
#define RV_MAP_PATH_AROUND_IMAGE_NAME (@"mapPathAround.png")
#define RV_MAP_PATH_AROUND_END_IMAGE_NAME (@"mapPathAroundEnd.png")
#define RV_MAP_PATH_TOOL_IMAGE_NAME (@"mapPathRoverTool.png")
#define RV_MAP_PATH_ANALYZE_IMAGE_NAME (@"mapPathAnalyze.png")

#define RV_IMAGES_VICTORY_SCREEN_CONTINUE_BUTTON (@"continueButton.png")
#define RV_IMAGES_VICTORY_SCREEN_CONTINUE_BUTTON_DOWN (@"continueButtonDown.png")
#define RV_IMAGES_VICTORY_SCREEN_INDIA_FAILURE (@"fIndia.png")
#define RV_IMAGES_VICTORY_SCREEN_INDIA_SUCCESS (@"sIndia.png")
#define RV_IMAGES_VICTORY_SCREEN_JACOB_FAILURE (@"fJacob.png")
#define RV_IMAGES_VICTORY_SCREEN_JACOB_SUCCESS (@"sJacob.png")
#define RV_IMAGES_VICTORY_SCREEN_MOON_THERMOMETER_3_MONTAGE_NAMES (@[@"moonThermometer11.png", @"moonThermometer0.png", @"moonThermometer9.png", @"moonThermometer8.png", @"moonThermometer7.png", @"moonThermometer6.png", @"moonThermometer5.png", @"moonThermometer4.png", @"moonThermometer3.png", @"moonThermometer2.png", @"moonThermometer1.png", @"moonThermometer0.png"])
#define RV_IMAGES_VICTORY_SCREEN_MOON_THERMOMETER_2_MONTAGE_NAMES (@[@"moonThermometer11.png", @"moonThermometer0.png", @"moonThermometer9.png", @"moonThermometer8.png", @"moonThermometer7.png", @"moonThermometer6.png", @"moonThermometer5.png", @"moonThermometer4.png", @"moonThermometer3.png", @"moonThermometer2.png", @"moonThermometer1.png"])
#define RV_IMAGES_VICTORY_SCREEN_MOON_THERMOMETER_1_MONTAGE_NAMES (@[@"moonThermometer11.png", @"moonThermometer0.png", @"moonThermometer9.png", @"moonThermometer8.png", @"moonThermometer7.png", @"moonThermometer6.png", @"moonThermometer5.png", @"moonThermometer4.png", @"moonThermometer3.png", @"moonThermometer2.png"])
#define RV_IMAGES_VICTORY_SCREEN_PLUTO_OBJECTIVE_1 (@"objective1Pluto.png")
#define RV_IMAGES_VICTORY_SCREEN_PLUTO_OBJECTIVE_2 (@"objective2Pluto.png")
#define RV_IMAGES_VICTORY_SCREEN_PLUTO_OBJECTIVE_3 (@"objective3Pluto.png")
#define RV_IMAGES_VICTORY_SCREEN_MARS_OBJECTIVE_1 (@"objectiveMars1.png")
#define RV_IMAGES_VICTORY_SCREEN_MARS_OBJECTIVE_2 (@"objectiveMars2.png")
#define RV_IMAGES_VICTORY_SCREEN_MARS_OBJECTIVE_3 (@"objectiveMars3.png")
#define RV_IMAGES_VICTORY_SCREEN_MARS_OBJECTIVE_4 (@"objectiveMars4.png")
#define RV_IMAGES_VICTORY_SCREEN_MOON_OBJECTIVE (@"objectiveMoon.png")
#define RV_IMAGES_VICTORY_SCREEN_TITAN_OBJECTIVE_1 (@"objectiveTitan1.png")
#define RV_IMAGES_VICTORY_SCREEN_TITAN_OBJECTIVE_2 (@"objectiveTitan2.png")
#define RV_IMAGES_VICTORY_SCREEN_OBJECTIVE_FAIL (@"objectiveFail.png")
#define RV_IMAGES_VICTORY_SCREEN_OBJECTIVE_FAIL_MARS (@"backgroundFailureMars.png")
#define RV_IMAGES_VICTORY_SCREEN_OBJECTIVE_FAIL_TITAN (@"backgroundFailureTitan.png")
#define RV_IMAGES_VICTORY_SCREEN_OBJECTIVE_FAIL_PLUTO (@"backgroundFailurePluto.png")
#define RV_IMAGES_VICTORY_SCREEN_OBJECTIVE_FAIL_MOON (@"backgroundFailureMoon.png")
#define RV_IMAGES_VICTORY_SCREEN_PLUTO_FLASH (@"plutoFlash.png")
#define RV_IMAGES_VICTORY_SCREEN_TRY_AGAIN_BUTTON (@"tryAgainButton.png")
#define RV_IMAGES_VICTORY_SCREEN_TRY_AGAIN_BUTTON_DOWN (@"tryAgainButtonDown.png")
#define RV_IMAGES_VICTORY_SCREEN_TWO_BUTTON_BACKGROUND (@"twoButtonBackground.png")
#define RV_IMAGES_VICTORY_SCREEN_TWO_BUTTON_CONTINUE (@"twoButtonContinue.png")
#define RV_IMAGES_VICTORY_SCREEN_TWO_BUTTON_CONTINUE_DOWN (@"twoButtonContinueDown.png")
#define RV_IMAGES_VICTORY_SCREEN_TWO_BUTTON_END (@"twoButtonEnd.png")
#define RV_IMAGES_VICTORY_SCREEN_TWO_BUTTON_END_DOWN (@"twoButtonEndDown.png")

#endif
